repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      stages: [commit]
      entry: poetry run isort
      args: [src, tests]
      language: system
      types: [python]
      pass_filenames: false

    - id: black
      name: black
      stages: [commit]
      entry: poetry run black
      args: [src, tests]
      language: system
      types: [python]
      pass_filenames: false

    - id: flake8
      name: flake8
      stages: [commit]
      entry: poetry run flake8
      args: [src, tests]
      language: system
      types: [python]
      pass_filenames: false

    - id: test
      name: test
      stages: [commit]
      entry: poetry run pytest
      language: system
      types: [python]
      pass_filenames: false