#!/usr/bin/env bash

#
# The script will prepare the project environment for development.
# Run this script from the project root directory.
#
# Usage:
#     $ cd path/to/project
#     $ . ./scripts/setup
#

echo "Creating virtualenv (.venv/) in project..."
poetry config --local virtualenvs.in-project true

echo "Installing package dependencies..."
poetry install

echo "Installing pre-commit hooks..."
if [ ! -d ".git" ]; then
git init
fi
poetry run pre-commit install -t pre-commit
poetry run pre-commit install -t pre-push